### ISSUE TITLE
Register onRequestFinished listener by default

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/har-export-trigger#16]
This is a follow-up for issue #8 
https://github.com/devtools-html/har-export-trigger/issues/8#issuecomment-390094126

Request-finished listener should be registered by default when the extension is initialized - i.e. when the Toolbox is opened (in devtools.js module)

Devtools back-end is instructed to collect all HTTP data if a listener is registered in advance, and so the first document request isn't missed.

Honza

**Comment by janodvarko** [comment]
@xmhubj @soulgalore can you please do quick review of the commit and give me green light for new release and upload on AMO? (the next version will be 0.6.1)

Thanks,
Honza

**Comment by soulgalore** [comment]
@janodvarko yep I tried it myself an hour ago and it works fine, the commit looks ok! Thanks!

**Comment by janodvarko** [comment]
HARExportTrigger 0.6.1 is uploaded on AMO (it should be available soon).
Honza

**Comment by soulgalore** [comment]
Hey @janodvarko I pushed it to our test server yesterday. A couple of things: 
* ~~We [got a user](https://github.com/sitespeedio/browsertime/issues/601) that used FF 60 and it stopped to work. Even though the aim for the plugin 61 one right, but the old version actually worked in 60 (but maybe works better in 61)~~. That was wrong, it worked in 60 since we used to use our own hack for the plugin.
* I could see on the test server that disabling choosing the netmonitor field has impact. Depending on the page, it makes first visual change 50-100 ms faster in our test environment.
* I rollbacked to 0.6.0: Our [test server](https://dashboard.sitespeed.io/) started to log a lot of errors when upgraded. I got a lot of errors trying to get the content size field in the HAR. I will try to recreate the problem later today and file a issue. See [#17](https://github.com/devtools-html/har-export-trigger/issues/17).

Best
Peter
