### ISSUE TITLE
startDateTime is a NULL object

### ISSUE THREAD

**Issue by asaverim8** [devtools-html/har-export-trigger#7]
Hey all,
Have you noticed that the startDateTime is a null object? (thus failing validation when .har file loaded).

![trigger_startdatetime](https://user-images.githubusercontent.com/36849361/36672144-85f13a6e-1afe-11e8-8835-5ac214183d15.png)

Anything i'm missing?

When desactivating har_validation:
![harviewer](https://user-images.githubusercontent.com/36849361/36672223-d08a67bc-1afe-11e8-9187-7c4eaadb1065.png)

Google-chrome v62 or v64
har-export-trigger: Last version

**Comment by janodvarko** [comment]
Can you please file a bug here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Netmonitor

I'll fix that.
Thanks,
Honza

**Comment by xmhubj** [comment]
I think this one it's related to browser chrome, on Firefox the `startedDateTime` is an ISO 8601 string, looks good.

![har_entry_starteddatetime](https://user-images.githubusercontent.com/15373664/36682798-0091d244-1b57-11e8-90f0-e8c3f101d4b6.jpg)

I once hit similar issue on Chrome last year, on Chrome `startedDateTime` returned by `chrome.devtools.network.getHAR` is a Date object, rather than a string. I opened an issue in Chromium project, see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=720273&can=2&q=API%20getHar&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).   They said it has been fixed....

**Comment by asaverim8** [comment]
+agreee for Firefox, everything seems fine

But for Chrome the startedDateTime is an object. Tested on chrome 62 / 63 / 64

![fert](https://user-images.githubusercontent.com/36849361/36686679-7cfb0056-1b27-11e8-8435-8a6e00fd8adf.png)

You made a toString() to the har message in devtools.js?

**Comment by xmhubj** [comment]
It was just a workaround, I had to iterate all the entries and pages in the har log, and use `toISOString` to convert startedDateTime to string one by one, a little bit ugly. Chrome should fix this issue, just like what Firefox does.

**Comment by janodvarko** [comment]
Thanks for the info!

Since this is Chrome bug (perhaps fixed) not related to Firefox and HARExportTrigger - I am closing this issue report.

Honza
